version: '2'
services:
    main:
        build: ./centos
        container_name: main
        ports:
            - "25565:25565"
        tty: true
        working_dir: "/minecraft"
        command: java -Xmx1024M -Xms1024M -jar minecraft_server.jar nogui

    web:
        image: httpd
        ports:
            - 80:80
        volumes:
            - ./htdocs:/usr/local/apache2/htdocs 

    node:
        build: node
        ports:
            - 8080:8080
        volumes:
            - ./node:/mnt
        volumes_from:
            - main
        tty: true
        #command: coffee /mnt/server.coffee
